### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#546] opened 2020-07-27 13:27 UTC
Hello,

I wanted to do range picking. When I start it, there is a error report since friday . It doesn´t matter if I use automatical or manual range picking.

Kind regards,
Eva

![Fehlermeldung](https://user-images.githubusercontent.com/60426010/88547035-798af400-d01d-11ea-96b5-a65d75356a09.jpg)

**Comment by evaziegler** [comment] 2020-07-27 13:29
Everytime I see this error I have to close the program and open it one more time. It is independent of the computer - I checked it with another one.

**Comment by hamed-musallam** [comment] 2020-08-10 08:20
@evaziegler 
I tested the auto/manual range picking  at the samples that we have in the left menu but i did not face your problem can you share with us the spectrum that you tested it and give you error when do the range picking.

**Comment by hamed-musallam** [comment] 2020-08-11 08:17
@evaziegler 
I tried the samples that you send it to me and the auto/manual range picking work with out any problem.

these are the sample that you sent it to me
[o-toluidin.zip](https://github.com/cheminfo/nmr-displayer/files/5055661/o-toluidin.zip)

**Comment by hamed-musallam** [comment] 2020-08-11 08:32
@evaziegler 
may be you did not use the last version, can you pull the last changes  using " git pull " then try again to import your sample.

**Comment by hamed-musallam** [comment] 2020-08-11 18:53
@evaziegler 
i thought that the problem in range picking (auto/manual) this what i understand from you description in this ticket, if the problem is in peak picking then you have to open new ticket here in githup and assign it to me and Luc

**Closed** 2020-09-16 08:42 UTC
