### ISSUE TITLE
Cannot add structure to re-loaded nmrium file

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#815] opened 2021-01-17 06:57 UTC
If I create an NMRIUM file from a set of 1D and 2D data, then do the ranges/zones picking and finally save it, after reloading the file, no molfile can be added without a crash. Also, it is not possible to do so by just drawing the structure using the integrated editor
[issue811.zip](https://github.com/cheminfo/nmr-displayer/files/5825683/issue811.zip)

**Comment by nes-cgn** [comment] 2021-01-17 07:00
If I first drag and drop also the structure plus the jcamp files, I can save the set

**Comment by hamed-musallam** [comment] 2021-01-18 10:50
@lpatiny 
Can you test it from your side because i can no reproduce it.

**Comment by lpatiny** [comment] 2021-01-18 13:33
@nes-cgn I can also not reproduce this problem.

If first drag / drop the nmrium file and then the molfile and I obtain this:

![image](https://user-images.githubusercontent.com/1484241/104921795-1493d380-599a-11eb-8ed0-3c10930e4af0.png)

**Comment by nes-cgn** [comment] 2021-01-19 12:07
From my side, the issue can be closed - I do not observe the problem anymore

**Comment by hamed-musallam** [comment] 2021-01-19 12:19
@nes-cgn 
I will close it right now and if you face it again you can just show us the case and I will trace the problem and solve it.

**Closed** 2021-01-19 12:19 UTC
Labels: bug
