### ISSUE TITLE
Crash in 2d

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#632] opened 2020-10-07 06:29 UTC
In this example:

http://localhost:3000/#/SamplesDashboard/cypd671yylh/undefinedcytisine2ddatacytisine2dhsqc_hmbcjson

1. Make autorange picking in 1H
2. Go to 13C and unselect the spectrum

![image](https://user-images.githubusercontent.com/1484241/95295303-1caa8600-0877-11eb-839d-4a938d5ba72e.png)

**Comment by hamed-musallam** [comment] 2020-10-20 14:10
@lpatiny 
I tried to reproduce the bug but I can not, so can you check it again because it may be fixed when fixed another bug. I will close this ticket for now.

**Closed by hamed-musallam** 2020-10-20 14:10 UTC
Labels: bug
